#task file for mysql_db role
   - name: Install MySQL database
     apt: name={{ item }} state=present
     with_items:
       - mysql-server
       - mysql-client

   - name: Start mysql service
     command: service mysql start


   - name: Create application database
     mysql_db: name={{ db_name }} state=present

   - name: create databse user
     mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: '*.*:ALL'
        state: 'present'
        host: "%"

